name: MSYS2
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        build_type: [release, debug]
        include:
          - libretro_build: 'DEBUG=0'
            build_type: release
          - libretro_build: 'DEBUG=1'
            build_type: debug
    runs-on: windows-latest
    env:
      MSYSTEM: CLANG64
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Configure git line endings
        shell: pwsh
        run: git config --global core.autocrlf false
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: CLANG64
          update: true
      - name: Install deps
        run: >-
          bash installdeps

      # Libretro build
      - name: Build libretro core
        run: make -C src/libretro ${{ matrix.libretro_build }} CC=clang CXX=clang++ SHARED="-shared -static-libgcc -static-libstdc++ -Wl,-no-undefined"
      - if: matrix.build_type == 'release'
        name: Upload libretro artifact
        uses: actions/upload-artifact@v4
        with:
          name: vbam-libretro-windows-x64
          path: src/libretro/vbam_libretro.dll
